name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install pyfred
      run: |
        pip install git+https://github.com/acourtneybrown/pyfred-cli@main

    - name: Package
      env:
        REPO: ${{ github.event.repository.name }}
      run: |
        pyfred package --name $REPO

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.alfredworkflow
        body: ${{ steps.github_release.outputs.changelog }}
